---
spring:
  application:
    name: kafka-demo

# Required connection configs for Kafka producer, consumer, and admin
  kafka:
    topics:
      user-topic: users
      order-topic: orders
      useroder-topic: user_order

    bootstrap-servers:
    - ${KAFKA_SERVERS}
    
    security:
      protocol: SASL_SSL
      
    properties:
      session:
        timeout:
          ms: 45000
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${KAFKA_CLIENT_ID} password=${KAFKA_CLIENT_SECRET};
      schema:
        registry:
          url: ${SR_URL}
      basic:
        auth:
          credentials:
            source: USER_INFO
          user:
            info: "${SR_CLIENT_ID}:${SR_CLIENT_SECRET}"
      
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        auto:
          register:
            schemas: false
        use:
          latest:
            version: true
      
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: demo-consumer-group       # Unique consumer group ID
      auto-offset-reset: latest       # Start from the earliest message
      enable-auto-commit: false
      properties:
        specific:
          avro:
            reader: true
    
    listener:
      ack-mode: manual                  # Manual acknowledgment mode
      type: batch 
